# See https://github.com/hvr/multi-ghc-travis
# The following enables several GHC versions to be tested; often it's enough to test only against the last release in a major GHC version. Feel free to omit lines listings versions you don't need/want testing for.
env:
 - GHCVER=7.6.2 CABALVER=1.16
 - GHCVER=7.6.3 CABALVER=1.16
 - GHCVER=7.8.2 CABALVER=1.18
 - GHCVER=7.8.3 CABALVER=1.18
 - GHCVER=head  CABALVER=1.20

matrix:
  allow_failures:
   - env: GHCVER=head  CABALVER=1.20

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - cabal --version

install:
 - travis_retry cabal update

script:
 - travis_retry cabal configure
 - travis_retry cabal build