# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, aeson, base64Bytestring, blazeHtml, emailValidate, lens
, mtl, QuickCheck, rawStringsQq, tasty, tastyHunit, tastyQuickcheck
, text, time, wreq
}:

cabal.mkDerivation (self: {
  pname = "mandrill";
  version = "0.1.0.3";
  src = ./.;
  buildDepends = [
    aeson base64Bytestring blazeHtml emailValidate lens mtl QuickCheck
    text time wreq
  ];
  testDepends = [
    aeson QuickCheck rawStringsQq tasty tastyHunit tastyQuickcheck text
  ];
  meta = {
    description = "Library for interfacing with the Mandrill JSON API";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
